### PR TITLE
Normalise MOVE_DISTANCE for multiple resolutions

### PR DESCRIPTION
**Pull request by codelif**
The before hard-coded value of 400, only accommodated 1920 width resolutions. So displays with higher or lower resolutions had to have the cursor move less or more respectively.

This commit sets MOVE_DISTANCE according the current monitor's resolution and scale, so experience is similar for all.

### CODE REVIEW

**Comment by codelif** [comment]
could you review please?

**Review by jVallant — APPROVED** [review]
sorry, for the late replay had some stuff to do this week. 

looks good. I actualy use a 4k display, but a less senstive default may work better

**Comment by codelif** [comment]
I tried a bunch of values, and I felt that a SCALE of `300/1920` was optimal. 

It didn't switch to multiple workspaces in one mouse flick, nor made switching a very obvious something you had to think about.

Ofcourse this may depend on your mouse sensitivity, acceleration and DPI.
Maybe in future, a calibration utility could be added to determine these variables.

**Comment by jVallant** [comment]
yeah, it's probably a personal preference and very much depends on the setup. 

A utility might be nice, but getting the value right would not take too much trial and error, just making the value a bit easier to configure via the command line would be enough i think. Making the value a percentage of the monitor width might also work better

**Pull request merged**
